Unleash/unleash-types-rs

- src/client_features.rs
As pointed out by https://github.com/Unleash/unleash-types-rs/security/code-scanning/1 this PR removes the unnecessary call to `.into()`
> fix: Remove unnecessary .into call

- .github/workflows/codequality.yaml
- .github/workflows/release.yaml
- .github/workflows/test-coverage.yaml
Update workflows to use Swatinem/rust-cache
The current cache setup doesn't cache the built artifacts causing us to have to build too much for small changes to the code. This PR is an attempt to optimise caching using rust-cache (an action optimised for caching rust-projects) rather than cache. The hope is that this will increase build speed for small changes
> ci: try to use rust-cache instead of github cache action

- Cargo.lock
- Cargo.toml
- src/client_features.rs
- src/client_metrics.rs
- src/frontend.rs
Since we plan on supporting OpenAPI in Unleash Edge, this PR adds an openapi feature to this project, which derives utoipa::ToSchema, simplifying using these return types in responses/requests in actix later.
See: https://crates.io/crates/utoipa
> feat: add openapi feature adding utoipa ToSchema

- CHANGELOG.md
Left over from `cargo smart-release`. It'd be nice to merge this stuff
> Release unleash-types v0.8.1

- README.md
- src/client_metrics.rs
Using u64 will require us to use [bigint](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint) on the server side. It may also bring other interoperability problems with other languages. u32 should be enough and compatible with most languages.
As specified in https://www.rfc-editor.org/rfc/rfc7159:
>    This specification allows implementations to set limits on the range
>    and precision of numbers accepted.  Since software that implements
>    IEEE 754-2008 binary64 (double precision) numbers [[IEEE754](https://www.rfc-editor.org/rfc/rfc7159#ref-IEEE754)] is
>    generally available and widely used, good interoperability can be
>    achieved by implementations that expect no more precision or range
>    than these provide, in the sense that …
> chore: u64 might require special treatment

- src/client_features.rs
- src/client_metrics.rs
Follow up on #21, use camelCase which in case we ever add more enums and u32 as discussed in the other PR
> chore: use u32 and camelCase

- src/client_features.rs
- src/client_metrics.rs
- src/frontend.rs
- src/lib.rs
The existing merge method prioritizes the left side of the operation, making sure that when we got new data we still kept the old one. This broke feature refreshing for Edge. 
This PR adds a right side favouring upsert method, which means that it will still retain data from left hand side of the operation, but features with same name as existing features in left hand side will be overwritten by this method.
> feat: Adds an upsert method that prioritizes new incoming data

- src/client_features.rs
Avoid serializing nulls the same way Unleash proper does.
> fix: Skip serializing if option is none

- examples/16-strategy-variants.json
- src/client_features.rs
- src/frontend.rs
- src/lib.rs
This adds support to handle the new strategy variant format defined in the client spec version 4.3.x
This patch will allow Edge to forward on this data and support server side SDKs to consume strategy variants via Edge
> feat: add support for strategy variants

- examples/17-dependent-features.json
- src/client_features.rs
- src/lib.rs
This change adds the `dependencies` property to the client feature
struct, opening the path for dependent feature toggles:
https://github.com/Unleash/unleash/issues/2255
> feat: add `dependencies` property to client feature struct

- src/client_features.rs
This adds the stickiness property to the strategy variant struct. This shouldn't be necessary because the SDKs **shouldn't** need this property. But the JS SDK does rely on it, due to a bug and rolling that back is tough.
This allows us to support those versions of the JS SDK without creating incompatible versions of Unleash/Edge/SDK that don't work together
> fix: add stickiness to strategy variants

- src/frontend.rs
Makes the structs used for Edge's front end responses camelCase. In practice, this only affects impressionData
> fix: convert frontend responses to camel case

- src/client_metrics.rs
Extends the metrics and registration structs to accept metadata fields for the new metrics we want to ingest.
I've chosen to make this type non optional - you really should be filling in these fields when you're ingesting this data. The serialization, however, will happily ignore the missing fields. This is all rolled up into a single flattened struct so that it's easier to keep these fields together
Depends on  #38 and  #39 - kept separate from these because those facilitate making the logic change smaller
> feat: extend metrics and registration with optional metadata

- src/client_features.rs
This change derives the Hash impl for Query. This should allow us to more easily use the query as a key in hash maps.
It's not currently behind the `hashes` flag because we already impl Hash for Feature and Segment without the flag. Of course, I'd be happy to move it behind the flag if we want it.
> feat:  impl hash for query

- CHANGELOG.md
- cliff.toml
What it says on the tin. Replace cargo-smart-release changelog with git cliff changelog
> task: migrate to git cliff for our changelog

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `unleash-types`: 0.15.0 -> 0.15.1
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- added meta field to ClientFeatures (#44) (by @chriswk) - #44
- migrate to git cliff for our changelog (#54) (by @chriswk) - #54
- Release plz workflow ([#45](https://github.com/Unleash/unleash-types-rs/pull/45)) (by @chriswk) - #45
- *(deps)* bump serde from 1.0.210 to 1.0.217 (#52) (by @dependabot[bot])
- *(deps)* bump actions/checkout from 3 to 4 (#49) (by @dependabot[bot])
- *(deps)* bump serde_json from 1.0.128 to 1.0.134 (#51) (by @dependabot[bot])
- *(deps)* bump github/codeql-action from 2 to 3 (#48) (by @dependabot[bot])
- *(deps)* bump xxhash-rust from 0.8.12 to 0.8.15 (#47) (by @dependabot[bot])
- *(deps)* bump chrono from 0.4.38 to 0.4.39 (#53) (by @dependabot[bot])
- added …
> chore: release v0.15.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `unleash-types`: 0.15.1 -> 0.15.2
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- client features delta schema (#57) (by @chriswk) - #57
* @chriswk
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.15.2

- examples/delta_base.json
- examples/delta_patch.json
- src/client_features.rs
- src/client_metrics.rs
So, after discussions with Simon. We realized that it's not only Yggdrasil that needs to know how to apply deltas, so this PR adds a `modify_in_place(&mut self, delta: &ClientFeaturesDelta)` which modifies in place and an `modify_and_copy(&self, delta: &ClientFeaturesDelta) -> ClientFeatures` which returns a new instance of ClientFeatures with the delta applied.
> feat: allow ClientFeatures to apply deltas to itself

- .gitignore
- src/client_features.rs
- src/client_metrics.rs
- src/lib.rs
Test to verify that delta is applied properly.
If you have existing `ClientFeature`
```
{name: "a", enabled : false}
```
And you get delta
```
{name: "a", enabled : true}
```
It is not updating the enabled value, due to how most likely how  `ClientFeature` eq/hash function works and merge function.
**Solution:**
Updated the merge function, to apply the old features to new features, since hashset does not overwrite if key exists.
> fix: apply delta not updating features

- src/client_features.rs
`modify_in_place` `and` `modify_and_copy` were sharing most of the code. Made a generic function to reduce duplication.
Now we have `apply_delta` and `create_from_delta`
> chore: refactor delta applying to be in generic function

- src/client_features.rs
Changing event id to u32, since we can only have positive numbers. Also adding helper method to get event id.
> feat: event_id finder for delta event

- examples/delta_patch.json
- src/client_features.rs
- src/lib.rs
We need project on feature removed event to filter events properly from edge.
Also ran cargo fmt on it.
> feat: add project to feature removed event

- .gitignore
- src/client_metrics.rs
Since instance_id can be overwritten and we need stable connection_id I'm introducing the same field we added to all frontend and backend SDKs (except from PHP/Next aka Lambda based model SDKs). I am not sure about the ConnectedVia since it uses instance_id but it's a concept I haven't seen before.
This PR is needed to unblock work on Edge that adds connectionId to registration payload and metrics payload as any other backend SDK. This is not used by Unleash yet until we get full SDK support.
> feat: add connection_id for ClientApplication and ClientMetrics

- src/client_features.rs
Changes deserialization of Context to allow json numbers (stringifies), ignore objects and booleans. Changes how nulls are matched but still removes null-properties.
For context native properties (user_id et al) numbers and booleans get converted to strings, objects, nulls, empty strings get None'd
> feat: looser frontend context deserialization to match unleash/api/frontend

- src/client_metrics.rs
ClientApplication projects has to be optional. The reason for that is that SDKs also use this type and they don't report projects. The same type is used for bulk app/metrics reporting and we add projects from the token and then it becomes Some type. With the current impl every SDK registering an application would get 400 bad request.
I added this type yesterday and started using today and found out it was wrong.
> feat: client application projects optional

- src/client_metrics.rs
This field is optional in Unleash but only if the field is completely missing. A null causes a bad validation error. Related to https://github.com/Unleash/unleash-edge/issues/1021, [this comment](https://github.com/Unleash/unleash-edge/issues/1021#issuecomment-3034743684)
> fix: skip serializing client application projects if they're missing
